/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authVerifyOtpRouteImport } from './routes/(auth)/verify-otp'
import { Route as authVerify2faRouteImport } from './routes/(auth)/verify-2fa'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninOtpRouteImport } from './routes/(auth)/signin-otp'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authMagicLinkRouteImport } from './routes/(auth)/magic-link'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as authChooseProviderRouteImport } from './routes/(auth)/choose-provider'
import { Route as appOnboardingRouteImport } from './routes/(app)/onboarding'
import { Route as appDashboardRouteRouteImport } from './routes/(app)/dashboard/route'
import { Route as appOrganizationsIndexRouteImport } from './routes/(app)/organizations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appOrganizationsCreateRouteImport } from './routes/(app)/organizations/create'
import { Route as appOrganizationsPathlessLayoutRouteRouteImport } from './routes/(app)/organizations/_pathlessLayout/route'
import { Route as appOrganizationsPathlessLayoutIdRouteRouteImport } from './routes/(app)/organizations/_pathlessLayout/$id/route'
import { Route as appOrganizationsPathlessLayoutIdSettingsRouteImport } from './routes/(app)/organizations/_pathlessLayout/$id/settings'
import { Route as appOrganizationsPathlessLayoutIdMembersRouteImport } from './routes/(app)/organizations/_pathlessLayout/$id/members'
import { Route as appOrganizationsPathlessLayoutIdDashboardRouteImport } from './routes/(app)/organizations/_pathlessLayout/$id/dashboard'

const appOrganizationsRouteImport = createFileRoute('/(app)/organizations')()

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appOrganizationsRoute = appOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => appRouteRoute,
} as any)
const authVerifyOtpRoute = authVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authVerify2faRoute = authVerify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninOtpRoute = authSigninOtpRouteImport.update({
  id: '/signin-otp',
  path: '/signin-otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authMagicLinkRoute = authMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authChooseProviderRoute = authChooseProviderRouteImport.update({
  id: '/choose-provider',
  path: '/choose-provider',
  getParentRoute: () => authRouteRoute,
} as any)
const appOnboardingRoute = appOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRouteRoute = appDashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrganizationsIndexRoute = appOrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appOrganizationsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appOrganizationsCreateRoute = appOrganizationsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appOrganizationsRoute,
} as any)
const appOrganizationsPathlessLayoutRouteRoute =
  appOrganizationsPathlessLayoutRouteRouteImport.update({
    id: '/_pathlessLayout',
    getParentRoute: () => appOrganizationsRoute,
  } as any)
const appOrganizationsPathlessLayoutIdRouteRoute =
  appOrganizationsPathlessLayoutIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => appOrganizationsPathlessLayoutRouteRoute,
  } as any)
const appOrganizationsPathlessLayoutIdSettingsRoute =
  appOrganizationsPathlessLayoutIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => appOrganizationsPathlessLayoutIdRouteRoute,
  } as any)
const appOrganizationsPathlessLayoutIdMembersRoute =
  appOrganizationsPathlessLayoutIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => appOrganizationsPathlessLayoutIdRouteRoute,
  } as any)
const appOrganizationsPathlessLayoutIdDashboardRoute =
  appOrganizationsPathlessLayoutIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => appOrganizationsPathlessLayoutIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRouteRoute
  '/onboarding': typeof appOnboardingRoute
  '/choose-provider': typeof authChooseProviderRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signin-otp': typeof authSigninOtpRoute
  '/signup': typeof authSignupRoute
  '/verify-2fa': typeof authVerify2faRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/organizations': typeof appOrganizationsPathlessLayoutRouteRouteWithChildren
  '/organizations/create': typeof appOrganizationsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/': typeof appOrganizationsIndexRoute
  '/organizations/$id': typeof appOrganizationsPathlessLayoutIdRouteRouteWithChildren
  '/organizations/$id/dashboard': typeof appOrganizationsPathlessLayoutIdDashboardRoute
  '/organizations/$id/members': typeof appOrganizationsPathlessLayoutIdMembersRoute
  '/organizations/$id/settings': typeof appOrganizationsPathlessLayoutIdSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRouteRoute
  '/onboarding': typeof appOnboardingRoute
  '/choose-provider': typeof authChooseProviderRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signin-otp': typeof authSigninOtpRoute
  '/signup': typeof authSignupRoute
  '/verify-2fa': typeof authVerify2faRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/organizations': typeof appOrganizationsIndexRoute
  '/organizations/create': typeof appOrganizationsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/$id': typeof appOrganizationsPathlessLayoutIdRouteRouteWithChildren
  '/organizations/$id/dashboard': typeof appOrganizationsPathlessLayoutIdDashboardRoute
  '/organizations/$id/members': typeof appOrganizationsPathlessLayoutIdMembersRoute
  '/organizations/$id/settings': typeof appOrganizationsPathlessLayoutIdSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/dashboard': typeof appDashboardRouteRoute
  '/(app)/onboarding': typeof appOnboardingRoute
  '/(auth)/choose-provider': typeof authChooseProviderRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/magic-link': typeof authMagicLinkRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signin-otp': typeof authSigninOtpRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-2fa': typeof authVerify2faRoute
  '/(auth)/verify-otp': typeof authVerifyOtpRoute
  '/(app)/organizations': typeof appOrganizationsRouteWithChildren
  '/(app)/organizations/_pathlessLayout': typeof appOrganizationsPathlessLayoutRouteRouteWithChildren
  '/(app)/organizations/create': typeof appOrganizationsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/organizations/': typeof appOrganizationsIndexRoute
  '/(app)/organizations/_pathlessLayout/$id': typeof appOrganizationsPathlessLayoutIdRouteRouteWithChildren
  '/(app)/organizations/_pathlessLayout/$id/dashboard': typeof appOrganizationsPathlessLayoutIdDashboardRoute
  '/(app)/organizations/_pathlessLayout/$id/members': typeof appOrganizationsPathlessLayoutIdMembersRoute
  '/(app)/organizations/_pathlessLayout/$id/settings': typeof appOrganizationsPathlessLayoutIdSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/choose-provider'
    | '/forgot-password'
    | '/magic-link'
    | '/reset-password'
    | '/signin'
    | '/signin-otp'
    | '/signup'
    | '/verify-2fa'
    | '/verify-otp'
    | '/organizations'
    | '/organizations/create'
    | '/api/auth/$'
    | '/organizations/'
    | '/organizations/$id'
    | '/organizations/$id/dashboard'
    | '/organizations/$id/members'
    | '/organizations/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/onboarding'
    | '/choose-provider'
    | '/forgot-password'
    | '/magic-link'
    | '/reset-password'
    | '/signin'
    | '/signin-otp'
    | '/signup'
    | '/verify-2fa'
    | '/verify-otp'
    | '/organizations'
    | '/organizations/create'
    | '/api/auth/$'
    | '/organizations/$id'
    | '/organizations/$id/dashboard'
    | '/organizations/$id/members'
    | '/organizations/$id/settings'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/(app)/dashboard'
    | '/(app)/onboarding'
    | '/(auth)/choose-provider'
    | '/(auth)/forgot-password'
    | '/(auth)/magic-link'
    | '/(auth)/reset-password'
    | '/(auth)/signin'
    | '/(auth)/signin-otp'
    | '/(auth)/signup'
    | '/(auth)/verify-2fa'
    | '/(auth)/verify-otp'
    | '/(app)/organizations'
    | '/(app)/organizations/_pathlessLayout'
    | '/(app)/organizations/create'
    | '/api/auth/$'
    | '/(app)/organizations/'
    | '/(app)/organizations/_pathlessLayout/$id'
    | '/(app)/organizations/_pathlessLayout/$id/dashboard'
    | '/(app)/organizations/_pathlessLayout/$id/members'
    | '/(app)/organizations/_pathlessLayout/$id/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/organizations': {
      id: '/(app)/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof appOrganizationsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/verify-otp': {
      id: '/(auth)/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof authVerifyOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/verify-2fa': {
      id: '/(auth)/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof authVerify2faRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin-otp': {
      id: '/(auth)/signin-otp'
      path: '/signin-otp'
      fullPath: '/signin-otp'
      preLoaderRoute: typeof authSigninOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/magic-link': {
      id: '/(auth)/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof authMagicLinkRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/choose-provider': {
      id: '/(auth)/choose-provider'
      path: '/choose-provider'
      fullPath: '/choose-provider'
      preLoaderRoute: typeof authChooseProviderRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/onboarding': {
      id: '/(app)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof appOnboardingRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/organizations/': {
      id: '/(app)/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof appOrganizationsIndexRouteImport
      parentRoute: typeof appOrganizationsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/organizations/create': {
      id: '/(app)/organizations/create'
      path: '/create'
      fullPath: '/organizations/create'
      preLoaderRoute: typeof appOrganizationsCreateRouteImport
      parentRoute: typeof appOrganizationsRoute
    }
    '/(app)/organizations/_pathlessLayout': {
      id: '/(app)/organizations/_pathlessLayout'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof appOrganizationsPathlessLayoutRouteRouteImport
      parentRoute: typeof appOrganizationsRoute
    }
    '/(app)/organizations/_pathlessLayout/$id': {
      id: '/(app)/organizations/_pathlessLayout/$id'
      path: '/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof appOrganizationsPathlessLayoutIdRouteRouteImport
      parentRoute: typeof appOrganizationsPathlessLayoutRouteRoute
    }
    '/(app)/organizations/_pathlessLayout/$id/settings': {
      id: '/(app)/organizations/_pathlessLayout/$id/settings'
      path: '/settings'
      fullPath: '/organizations/$id/settings'
      preLoaderRoute: typeof appOrganizationsPathlessLayoutIdSettingsRouteImport
      parentRoute: typeof appOrganizationsPathlessLayoutIdRouteRoute
    }
    '/(app)/organizations/_pathlessLayout/$id/members': {
      id: '/(app)/organizations/_pathlessLayout/$id/members'
      path: '/members'
      fullPath: '/organizations/$id/members'
      preLoaderRoute: typeof appOrganizationsPathlessLayoutIdMembersRouteImport
      parentRoute: typeof appOrganizationsPathlessLayoutIdRouteRoute
    }
    '/(app)/organizations/_pathlessLayout/$id/dashboard': {
      id: '/(app)/organizations/_pathlessLayout/$id/dashboard'
      path: '/dashboard'
      fullPath: '/organizations/$id/dashboard'
      preLoaderRoute: typeof appOrganizationsPathlessLayoutIdDashboardRouteImport
      parentRoute: typeof appOrganizationsPathlessLayoutIdRouteRoute
    }
  }
}

interface appOrganizationsPathlessLayoutIdRouteRouteChildren {
  appOrganizationsPathlessLayoutIdDashboardRoute: typeof appOrganizationsPathlessLayoutIdDashboardRoute
  appOrganizationsPathlessLayoutIdMembersRoute: typeof appOrganizationsPathlessLayoutIdMembersRoute
  appOrganizationsPathlessLayoutIdSettingsRoute: typeof appOrganizationsPathlessLayoutIdSettingsRoute
}

const appOrganizationsPathlessLayoutIdRouteRouteChildren: appOrganizationsPathlessLayoutIdRouteRouteChildren =
  {
    appOrganizationsPathlessLayoutIdDashboardRoute:
      appOrganizationsPathlessLayoutIdDashboardRoute,
    appOrganizationsPathlessLayoutIdMembersRoute:
      appOrganizationsPathlessLayoutIdMembersRoute,
    appOrganizationsPathlessLayoutIdSettingsRoute:
      appOrganizationsPathlessLayoutIdSettingsRoute,
  }

const appOrganizationsPathlessLayoutIdRouteRouteWithChildren =
  appOrganizationsPathlessLayoutIdRouteRoute._addFileChildren(
    appOrganizationsPathlessLayoutIdRouteRouteChildren,
  )

interface appOrganizationsPathlessLayoutRouteRouteChildren {
  appOrganizationsPathlessLayoutIdRouteRoute: typeof appOrganizationsPathlessLayoutIdRouteRouteWithChildren
}

const appOrganizationsPathlessLayoutRouteRouteChildren: appOrganizationsPathlessLayoutRouteRouteChildren =
  {
    appOrganizationsPathlessLayoutIdRouteRoute:
      appOrganizationsPathlessLayoutIdRouteRouteWithChildren,
  }

const appOrganizationsPathlessLayoutRouteRouteWithChildren =
  appOrganizationsPathlessLayoutRouteRoute._addFileChildren(
    appOrganizationsPathlessLayoutRouteRouteChildren,
  )

interface appOrganizationsRouteChildren {
  appOrganizationsPathlessLayoutRouteRoute: typeof appOrganizationsPathlessLayoutRouteRouteWithChildren
  appOrganizationsCreateRoute: typeof appOrganizationsCreateRoute
  appOrganizationsIndexRoute: typeof appOrganizationsIndexRoute
}

const appOrganizationsRouteChildren: appOrganizationsRouteChildren = {
  appOrganizationsPathlessLayoutRouteRoute:
    appOrganizationsPathlessLayoutRouteRouteWithChildren,
  appOrganizationsCreateRoute: appOrganizationsCreateRoute,
  appOrganizationsIndexRoute: appOrganizationsIndexRoute,
}

const appOrganizationsRouteWithChildren =
  appOrganizationsRoute._addFileChildren(appOrganizationsRouteChildren)

interface appRouteRouteChildren {
  appDashboardRouteRoute: typeof appDashboardRouteRoute
  appOnboardingRoute: typeof appOnboardingRoute
  appOrganizationsRoute: typeof appOrganizationsRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardRouteRoute: appDashboardRouteRoute,
  appOnboardingRoute: appOnboardingRoute,
  appOrganizationsRoute: appOrganizationsRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authChooseProviderRoute: typeof authChooseProviderRoute
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authMagicLinkRoute: typeof authMagicLinkRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSigninOtpRoute: typeof authSigninOtpRoute
  authSignupRoute: typeof authSignupRoute
  authVerify2faRoute: typeof authVerify2faRoute
  authVerifyOtpRoute: typeof authVerifyOtpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authChooseProviderRoute: authChooseProviderRoute,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authMagicLinkRoute: authMagicLinkRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSigninOtpRoute: authSigninOtpRoute,
  authSignupRoute: authSignupRoute,
  authVerify2faRoute: authVerify2faRoute,
  authVerifyOtpRoute: authVerifyOtpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
