/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as authRouteRouteImport } from './routes/(auth)/route'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authVerifyOtpRouteImport } from './routes/(auth)/verify-otp'
import { Route as authVerify2faRouteImport } from './routes/(auth)/verify-2fa'
import { Route as authSignupRouteImport } from './routes/(auth)/signup'
import { Route as authSigninOtpRouteImport } from './routes/(auth)/signin-otp'
import { Route as authSigninRouteImport } from './routes/(auth)/signin'
import { Route as authResetPasswordRouteImport } from './routes/(auth)/reset-password'
import { Route as authMagicLinkRouteImport } from './routes/(auth)/magic-link'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as appOnboardingRouteImport } from './routes/(app)/onboarding'
import { Route as appOrganizationsIndexRouteImport } from './routes/(app)/organizations/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as appOrganizationsCreateRouteImport } from './routes/(app)/organizations/create'
import { Route as appProfilePathlessLayoutRouteRouteImport } from './routes/(app)/profile/_pathlessLayout/route'
import { Route as appOrganizationsPathlessLayoutRouteRouteImport } from './routes/(app)/organizations/_pathlessLayout/route'
import { Route as appProfilePathlessLayoutSecurityRouteImport } from './routes/(app)/profile/_pathlessLayout/security'
import { Route as appProfilePathlessLayoutProvidersRouteImport } from './routes/(app)/profile/_pathlessLayout/providers'
import { Route as appProfilePathlessLayoutPersonalDetailsRouteImport } from './routes/(app)/profile/_pathlessLayout/personal-details'
import { Route as appProfilePathlessLayoutDangerZoneRouteImport } from './routes/(app)/profile/_pathlessLayout/danger-zone'
import { Route as appProfilePathlessLayoutApiKeysRouteImport } from './routes/(app)/profile/_pathlessLayout/api-keys'
import { Route as appProfilePathlessLayoutActiveSessionsRouteImport } from './routes/(app)/profile/_pathlessLayout/active-sessions'
import { Route as appOrganizationsPathlessLayoutIdRouteRouteImport } from './routes/(app)/organizations/_pathlessLayout/$id/route'
import { Route as appOrganizationsPathlessLayoutIdDashboardRouteImport } from './routes/(app)/organizations/_pathlessLayout/$id/dashboard'
import { Route as appOrganizationsPathlessLayoutIdSettingsIndexRouteImport } from './routes/(app)/organizations/_pathlessLayout/$id/settings/index'
import { Route as appOrganizationsPathlessLayoutIdMembersIndexRouteImport } from './routes/(app)/organizations/_pathlessLayout/$id/members/index'

const appProfileRouteImport = createFileRoute('/(app)/profile')()
const appOrganizationsRouteImport = createFileRoute('/(app)/organizations')()

const authRouteRoute = authRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => rootRouteImport,
} as any)
const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const appProfileRoute = appProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrganizationsRoute = appOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => appRouteRoute,
} as any)
const authVerifyOtpRoute = authVerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authVerify2faRoute = authVerify2faRouteImport.update({
  id: '/verify-2fa',
  path: '/verify-2fa',
  getParentRoute: () => authRouteRoute,
} as any)
const authSignupRoute = authSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninOtpRoute = authSigninOtpRouteImport.update({
  id: '/signin-otp',
  path: '/signin-otp',
  getParentRoute: () => authRouteRoute,
} as any)
const authSigninRoute = authSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => authRouteRoute,
} as any)
const authResetPasswordRoute = authResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => authRouteRoute,
} as any)
const authMagicLinkRoute = authMagicLinkRouteImport.update({
  id: '/magic-link',
  path: '/magic-link',
  getParentRoute: () => authRouteRoute,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => authRouteRoute,
} as any)
const appOnboardingRoute = appOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => appRouteRoute,
} as any)
const appOrganizationsIndexRoute = appOrganizationsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appOrganizationsRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const appOrganizationsCreateRoute = appOrganizationsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => appOrganizationsRoute,
} as any)
const appProfilePathlessLayoutRouteRoute =
  appProfilePathlessLayoutRouteRouteImport.update({
    id: '/_pathlessLayout',
    getParentRoute: () => appProfileRoute,
  } as any)
const appOrganizationsPathlessLayoutRouteRoute =
  appOrganizationsPathlessLayoutRouteRouteImport.update({
    id: '/_pathlessLayout',
    getParentRoute: () => appOrganizationsRoute,
  } as any)
const appProfilePathlessLayoutSecurityRoute =
  appProfilePathlessLayoutSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => appProfilePathlessLayoutRouteRoute,
  } as any)
const appProfilePathlessLayoutProvidersRoute =
  appProfilePathlessLayoutProvidersRouteImport.update({
    id: '/providers',
    path: '/providers',
    getParentRoute: () => appProfilePathlessLayoutRouteRoute,
  } as any)
const appProfilePathlessLayoutPersonalDetailsRoute =
  appProfilePathlessLayoutPersonalDetailsRouteImport.update({
    id: '/personal-details',
    path: '/personal-details',
    getParentRoute: () => appProfilePathlessLayoutRouteRoute,
  } as any)
const appProfilePathlessLayoutDangerZoneRoute =
  appProfilePathlessLayoutDangerZoneRouteImport.update({
    id: '/danger-zone',
    path: '/danger-zone',
    getParentRoute: () => appProfilePathlessLayoutRouteRoute,
  } as any)
const appProfilePathlessLayoutApiKeysRoute =
  appProfilePathlessLayoutApiKeysRouteImport.update({
    id: '/api-keys',
    path: '/api-keys',
    getParentRoute: () => appProfilePathlessLayoutRouteRoute,
  } as any)
const appProfilePathlessLayoutActiveSessionsRoute =
  appProfilePathlessLayoutActiveSessionsRouteImport.update({
    id: '/active-sessions',
    path: '/active-sessions',
    getParentRoute: () => appProfilePathlessLayoutRouteRoute,
  } as any)
const appOrganizationsPathlessLayoutIdRouteRoute =
  appOrganizationsPathlessLayoutIdRouteRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => appOrganizationsPathlessLayoutRouteRoute,
  } as any)
const appOrganizationsPathlessLayoutIdDashboardRoute =
  appOrganizationsPathlessLayoutIdDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => appOrganizationsPathlessLayoutIdRouteRoute,
  } as any)
const appOrganizationsPathlessLayoutIdSettingsIndexRoute =
  appOrganizationsPathlessLayoutIdSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => appOrganizationsPathlessLayoutIdRouteRoute,
  } as any)
const appOrganizationsPathlessLayoutIdMembersIndexRoute =
  appOrganizationsPathlessLayoutIdMembersIndexRouteImport.update({
    id: '/members/',
    path: '/members/',
    getParentRoute: () => appOrganizationsPathlessLayoutIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof appOnboardingRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signin-otp': typeof authSigninOtpRoute
  '/signup': typeof authSignupRoute
  '/verify-2fa': typeof authVerify2faRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/organizations': typeof appOrganizationsPathlessLayoutRouteRouteWithChildren
  '/profile': typeof appProfilePathlessLayoutRouteRouteWithChildren
  '/organizations/create': typeof appOrganizationsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/': typeof appOrganizationsIndexRoute
  '/organizations/$id': typeof appOrganizationsPathlessLayoutIdRouteRouteWithChildren
  '/profile/active-sessions': typeof appProfilePathlessLayoutActiveSessionsRoute
  '/profile/api-keys': typeof appProfilePathlessLayoutApiKeysRoute
  '/profile/danger-zone': typeof appProfilePathlessLayoutDangerZoneRoute
  '/profile/personal-details': typeof appProfilePathlessLayoutPersonalDetailsRoute
  '/profile/providers': typeof appProfilePathlessLayoutProvidersRoute
  '/profile/security': typeof appProfilePathlessLayoutSecurityRoute
  '/organizations/$id/dashboard': typeof appOrganizationsPathlessLayoutIdDashboardRoute
  '/organizations/$id/members': typeof appOrganizationsPathlessLayoutIdMembersIndexRoute
  '/organizations/$id/settings': typeof appOrganizationsPathlessLayoutIdSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof appOnboardingRoute
  '/forgot-password': typeof authForgotPasswordRoute
  '/magic-link': typeof authMagicLinkRoute
  '/reset-password': typeof authResetPasswordRoute
  '/signin': typeof authSigninRoute
  '/signin-otp': typeof authSigninOtpRoute
  '/signup': typeof authSignupRoute
  '/verify-2fa': typeof authVerify2faRoute
  '/verify-otp': typeof authVerifyOtpRoute
  '/organizations': typeof appOrganizationsIndexRoute
  '/profile': typeof appProfilePathlessLayoutRouteRouteWithChildren
  '/organizations/create': typeof appOrganizationsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/organizations/$id': typeof appOrganizationsPathlessLayoutIdRouteRouteWithChildren
  '/profile/active-sessions': typeof appProfilePathlessLayoutActiveSessionsRoute
  '/profile/api-keys': typeof appProfilePathlessLayoutApiKeysRoute
  '/profile/danger-zone': typeof appProfilePathlessLayoutDangerZoneRoute
  '/profile/personal-details': typeof appProfilePathlessLayoutPersonalDetailsRoute
  '/profile/providers': typeof appProfilePathlessLayoutProvidersRoute
  '/profile/security': typeof appProfilePathlessLayoutSecurityRoute
  '/organizations/$id/dashboard': typeof appOrganizationsPathlessLayoutIdDashboardRoute
  '/organizations/$id/members': typeof appOrganizationsPathlessLayoutIdMembersIndexRoute
  '/organizations/$id/settings': typeof appOrganizationsPathlessLayoutIdSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(auth)': typeof authRouteRouteWithChildren
  '/(app)/onboarding': typeof appOnboardingRoute
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/magic-link': typeof authMagicLinkRoute
  '/(auth)/reset-password': typeof authResetPasswordRoute
  '/(auth)/signin': typeof authSigninRoute
  '/(auth)/signin-otp': typeof authSigninOtpRoute
  '/(auth)/signup': typeof authSignupRoute
  '/(auth)/verify-2fa': typeof authVerify2faRoute
  '/(auth)/verify-otp': typeof authVerifyOtpRoute
  '/(app)/organizations': typeof appOrganizationsRouteWithChildren
  '/(app)/organizations/_pathlessLayout': typeof appOrganizationsPathlessLayoutRouteRouteWithChildren
  '/(app)/profile': typeof appProfileRouteWithChildren
  '/(app)/profile/_pathlessLayout': typeof appProfilePathlessLayoutRouteRouteWithChildren
  '/(app)/organizations/create': typeof appOrganizationsCreateRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/(app)/organizations/': typeof appOrganizationsIndexRoute
  '/(app)/organizations/_pathlessLayout/$id': typeof appOrganizationsPathlessLayoutIdRouteRouteWithChildren
  '/(app)/profile/_pathlessLayout/active-sessions': typeof appProfilePathlessLayoutActiveSessionsRoute
  '/(app)/profile/_pathlessLayout/api-keys': typeof appProfilePathlessLayoutApiKeysRoute
  '/(app)/profile/_pathlessLayout/danger-zone': typeof appProfilePathlessLayoutDangerZoneRoute
  '/(app)/profile/_pathlessLayout/personal-details': typeof appProfilePathlessLayoutPersonalDetailsRoute
  '/(app)/profile/_pathlessLayout/providers': typeof appProfilePathlessLayoutProvidersRoute
  '/(app)/profile/_pathlessLayout/security': typeof appProfilePathlessLayoutSecurityRoute
  '/(app)/organizations/_pathlessLayout/$id/dashboard': typeof appOrganizationsPathlessLayoutIdDashboardRoute
  '/(app)/organizations/_pathlessLayout/$id/members/': typeof appOrganizationsPathlessLayoutIdMembersIndexRoute
  '/(app)/organizations/_pathlessLayout/$id/settings/': typeof appOrganizationsPathlessLayoutIdSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/forgot-password'
    | '/magic-link'
    | '/reset-password'
    | '/signin'
    | '/signin-otp'
    | '/signup'
    | '/verify-2fa'
    | '/verify-otp'
    | '/organizations'
    | '/profile'
    | '/organizations/create'
    | '/api/auth/$'
    | '/organizations/'
    | '/organizations/$id'
    | '/profile/active-sessions'
    | '/profile/api-keys'
    | '/profile/danger-zone'
    | '/profile/personal-details'
    | '/profile/providers'
    | '/profile/security'
    | '/organizations/$id/dashboard'
    | '/organizations/$id/members'
    | '/organizations/$id/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/forgot-password'
    | '/magic-link'
    | '/reset-password'
    | '/signin'
    | '/signin-otp'
    | '/signup'
    | '/verify-2fa'
    | '/verify-otp'
    | '/organizations'
    | '/profile'
    | '/organizations/create'
    | '/api/auth/$'
    | '/organizations/$id'
    | '/profile/active-sessions'
    | '/profile/api-keys'
    | '/profile/danger-zone'
    | '/profile/personal-details'
    | '/profile/providers'
    | '/profile/security'
    | '/organizations/$id/dashboard'
    | '/organizations/$id/members'
    | '/organizations/$id/settings'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(auth)'
    | '/(app)/onboarding'
    | '/(auth)/forgot-password'
    | '/(auth)/magic-link'
    | '/(auth)/reset-password'
    | '/(auth)/signin'
    | '/(auth)/signin-otp'
    | '/(auth)/signup'
    | '/(auth)/verify-2fa'
    | '/(auth)/verify-otp'
    | '/(app)/organizations'
    | '/(app)/organizations/_pathlessLayout'
    | '/(app)/profile'
    | '/(app)/profile/_pathlessLayout'
    | '/(app)/organizations/create'
    | '/api/auth/$'
    | '/(app)/organizations/'
    | '/(app)/organizations/_pathlessLayout/$id'
    | '/(app)/profile/_pathlessLayout/active-sessions'
    | '/(app)/profile/_pathlessLayout/api-keys'
    | '/(app)/profile/_pathlessLayout/danger-zone'
    | '/(app)/profile/_pathlessLayout/personal-details'
    | '/(app)/profile/_pathlessLayout/providers'
    | '/(app)/profile/_pathlessLayout/security'
    | '/(app)/organizations/_pathlessLayout/$id/dashboard'
    | '/(app)/organizations/_pathlessLayout/$id/members/'
    | '/(app)/organizations/_pathlessLayout/$id/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  authRouteRoute: typeof authRouteRouteWithChildren
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(auth)': {
      id: '/(auth)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof authRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/profile': {
      id: '/(app)/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfileRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/organizations': {
      id: '/(app)/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof appOrganizationsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(auth)/verify-otp': {
      id: '/(auth)/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof authVerifyOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/verify-2fa': {
      id: '/(auth)/verify-2fa'
      path: '/verify-2fa'
      fullPath: '/verify-2fa'
      preLoaderRoute: typeof authVerify2faRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signup': {
      id: '/(auth)/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin-otp': {
      id: '/(auth)/signin-otp'
      path: '/signin-otp'
      fullPath: '/signin-otp'
      preLoaderRoute: typeof authSigninOtpRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/signin': {
      id: '/(auth)/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/reset-password': {
      id: '/(auth)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof authResetPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/magic-link': {
      id: '/(auth)/magic-link'
      path: '/magic-link'
      fullPath: '/magic-link'
      preLoaderRoute: typeof authMagicLinkRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof authRouteRoute
    }
    '/(app)/onboarding': {
      id: '/(app)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof appOnboardingRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/organizations/': {
      id: '/(app)/organizations/'
      path: '/'
      fullPath: '/organizations/'
      preLoaderRoute: typeof appOrganizationsIndexRouteImport
      parentRoute: typeof appOrganizationsRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/organizations/create': {
      id: '/(app)/organizations/create'
      path: '/create'
      fullPath: '/organizations/create'
      preLoaderRoute: typeof appOrganizationsCreateRouteImport
      parentRoute: typeof appOrganizationsRoute
    }
    '/(app)/profile/_pathlessLayout': {
      id: '/(app)/profile/_pathlessLayout'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof appProfilePathlessLayoutRouteRouteImport
      parentRoute: typeof appProfileRoute
    }
    '/(app)/organizations/_pathlessLayout': {
      id: '/(app)/organizations/_pathlessLayout'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof appOrganizationsPathlessLayoutRouteRouteImport
      parentRoute: typeof appOrganizationsRoute
    }
    '/(app)/profile/_pathlessLayout/security': {
      id: '/(app)/profile/_pathlessLayout/security'
      path: '/security'
      fullPath: '/profile/security'
      preLoaderRoute: typeof appProfilePathlessLayoutSecurityRouteImport
      parentRoute: typeof appProfilePathlessLayoutRouteRoute
    }
    '/(app)/profile/_pathlessLayout/providers': {
      id: '/(app)/profile/_pathlessLayout/providers'
      path: '/providers'
      fullPath: '/profile/providers'
      preLoaderRoute: typeof appProfilePathlessLayoutProvidersRouteImport
      parentRoute: typeof appProfilePathlessLayoutRouteRoute
    }
    '/(app)/profile/_pathlessLayout/personal-details': {
      id: '/(app)/profile/_pathlessLayout/personal-details'
      path: '/personal-details'
      fullPath: '/profile/personal-details'
      preLoaderRoute: typeof appProfilePathlessLayoutPersonalDetailsRouteImport
      parentRoute: typeof appProfilePathlessLayoutRouteRoute
    }
    '/(app)/profile/_pathlessLayout/danger-zone': {
      id: '/(app)/profile/_pathlessLayout/danger-zone'
      path: '/danger-zone'
      fullPath: '/profile/danger-zone'
      preLoaderRoute: typeof appProfilePathlessLayoutDangerZoneRouteImport
      parentRoute: typeof appProfilePathlessLayoutRouteRoute
    }
    '/(app)/profile/_pathlessLayout/api-keys': {
      id: '/(app)/profile/_pathlessLayout/api-keys'
      path: '/api-keys'
      fullPath: '/profile/api-keys'
      preLoaderRoute: typeof appProfilePathlessLayoutApiKeysRouteImport
      parentRoute: typeof appProfilePathlessLayoutRouteRoute
    }
    '/(app)/profile/_pathlessLayout/active-sessions': {
      id: '/(app)/profile/_pathlessLayout/active-sessions'
      path: '/active-sessions'
      fullPath: '/profile/active-sessions'
      preLoaderRoute: typeof appProfilePathlessLayoutActiveSessionsRouteImport
      parentRoute: typeof appProfilePathlessLayoutRouteRoute
    }
    '/(app)/organizations/_pathlessLayout/$id': {
      id: '/(app)/organizations/_pathlessLayout/$id'
      path: '/$id'
      fullPath: '/organizations/$id'
      preLoaderRoute: typeof appOrganizationsPathlessLayoutIdRouteRouteImport
      parentRoute: typeof appOrganizationsPathlessLayoutRouteRoute
    }
    '/(app)/organizations/_pathlessLayout/$id/dashboard': {
      id: '/(app)/organizations/_pathlessLayout/$id/dashboard'
      path: '/dashboard'
      fullPath: '/organizations/$id/dashboard'
      preLoaderRoute: typeof appOrganizationsPathlessLayoutIdDashboardRouteImport
      parentRoute: typeof appOrganizationsPathlessLayoutIdRouteRoute
    }
    '/(app)/organizations/_pathlessLayout/$id/settings/': {
      id: '/(app)/organizations/_pathlessLayout/$id/settings/'
      path: '/settings'
      fullPath: '/organizations/$id/settings'
      preLoaderRoute: typeof appOrganizationsPathlessLayoutIdSettingsIndexRouteImport
      parentRoute: typeof appOrganizationsPathlessLayoutIdRouteRoute
    }
    '/(app)/organizations/_pathlessLayout/$id/members/': {
      id: '/(app)/organizations/_pathlessLayout/$id/members/'
      path: '/members'
      fullPath: '/organizations/$id/members'
      preLoaderRoute: typeof appOrganizationsPathlessLayoutIdMembersIndexRouteImport
      parentRoute: typeof appOrganizationsPathlessLayoutIdRouteRoute
    }
  }
}

interface appOrganizationsPathlessLayoutIdRouteRouteChildren {
  appOrganizationsPathlessLayoutIdDashboardRoute: typeof appOrganizationsPathlessLayoutIdDashboardRoute
  appOrganizationsPathlessLayoutIdMembersIndexRoute: typeof appOrganizationsPathlessLayoutIdMembersIndexRoute
  appOrganizationsPathlessLayoutIdSettingsIndexRoute: typeof appOrganizationsPathlessLayoutIdSettingsIndexRoute
}

const appOrganizationsPathlessLayoutIdRouteRouteChildren: appOrganizationsPathlessLayoutIdRouteRouteChildren =
  {
    appOrganizationsPathlessLayoutIdDashboardRoute:
      appOrganizationsPathlessLayoutIdDashboardRoute,
    appOrganizationsPathlessLayoutIdMembersIndexRoute:
      appOrganizationsPathlessLayoutIdMembersIndexRoute,
    appOrganizationsPathlessLayoutIdSettingsIndexRoute:
      appOrganizationsPathlessLayoutIdSettingsIndexRoute,
  }

const appOrganizationsPathlessLayoutIdRouteRouteWithChildren =
  appOrganizationsPathlessLayoutIdRouteRoute._addFileChildren(
    appOrganizationsPathlessLayoutIdRouteRouteChildren,
  )

interface appOrganizationsPathlessLayoutRouteRouteChildren {
  appOrganizationsPathlessLayoutIdRouteRoute: typeof appOrganizationsPathlessLayoutIdRouteRouteWithChildren
}

const appOrganizationsPathlessLayoutRouteRouteChildren: appOrganizationsPathlessLayoutRouteRouteChildren =
  {
    appOrganizationsPathlessLayoutIdRouteRoute:
      appOrganizationsPathlessLayoutIdRouteRouteWithChildren,
  }

const appOrganizationsPathlessLayoutRouteRouteWithChildren =
  appOrganizationsPathlessLayoutRouteRoute._addFileChildren(
    appOrganizationsPathlessLayoutRouteRouteChildren,
  )

interface appOrganizationsRouteChildren {
  appOrganizationsPathlessLayoutRouteRoute: typeof appOrganizationsPathlessLayoutRouteRouteWithChildren
  appOrganizationsCreateRoute: typeof appOrganizationsCreateRoute
  appOrganizationsIndexRoute: typeof appOrganizationsIndexRoute
}

const appOrganizationsRouteChildren: appOrganizationsRouteChildren = {
  appOrganizationsPathlessLayoutRouteRoute:
    appOrganizationsPathlessLayoutRouteRouteWithChildren,
  appOrganizationsCreateRoute: appOrganizationsCreateRoute,
  appOrganizationsIndexRoute: appOrganizationsIndexRoute,
}

const appOrganizationsRouteWithChildren =
  appOrganizationsRoute._addFileChildren(appOrganizationsRouteChildren)

interface appProfilePathlessLayoutRouteRouteChildren {
  appProfilePathlessLayoutActiveSessionsRoute: typeof appProfilePathlessLayoutActiveSessionsRoute
  appProfilePathlessLayoutApiKeysRoute: typeof appProfilePathlessLayoutApiKeysRoute
  appProfilePathlessLayoutDangerZoneRoute: typeof appProfilePathlessLayoutDangerZoneRoute
  appProfilePathlessLayoutPersonalDetailsRoute: typeof appProfilePathlessLayoutPersonalDetailsRoute
  appProfilePathlessLayoutProvidersRoute: typeof appProfilePathlessLayoutProvidersRoute
  appProfilePathlessLayoutSecurityRoute: typeof appProfilePathlessLayoutSecurityRoute
}

const appProfilePathlessLayoutRouteRouteChildren: appProfilePathlessLayoutRouteRouteChildren =
  {
    appProfilePathlessLayoutActiveSessionsRoute:
      appProfilePathlessLayoutActiveSessionsRoute,
    appProfilePathlessLayoutApiKeysRoute: appProfilePathlessLayoutApiKeysRoute,
    appProfilePathlessLayoutDangerZoneRoute:
      appProfilePathlessLayoutDangerZoneRoute,
    appProfilePathlessLayoutPersonalDetailsRoute:
      appProfilePathlessLayoutPersonalDetailsRoute,
    appProfilePathlessLayoutProvidersRoute:
      appProfilePathlessLayoutProvidersRoute,
    appProfilePathlessLayoutSecurityRoute:
      appProfilePathlessLayoutSecurityRoute,
  }

const appProfilePathlessLayoutRouteRouteWithChildren =
  appProfilePathlessLayoutRouteRoute._addFileChildren(
    appProfilePathlessLayoutRouteRouteChildren,
  )

interface appProfileRouteChildren {
  appProfilePathlessLayoutRouteRoute: typeof appProfilePathlessLayoutRouteRouteWithChildren
}

const appProfileRouteChildren: appProfileRouteChildren = {
  appProfilePathlessLayoutRouteRoute:
    appProfilePathlessLayoutRouteRouteWithChildren,
}

const appProfileRouteWithChildren = appProfileRoute._addFileChildren(
  appProfileRouteChildren,
)

interface appRouteRouteChildren {
  appOnboardingRoute: typeof appOnboardingRoute
  appOrganizationsRoute: typeof appOrganizationsRouteWithChildren
  appProfileRoute: typeof appProfileRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appOnboardingRoute: appOnboardingRoute,
  appOrganizationsRoute: appOrganizationsRouteWithChildren,
  appProfileRoute: appProfileRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

interface authRouteRouteChildren {
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authMagicLinkRoute: typeof authMagicLinkRoute
  authResetPasswordRoute: typeof authResetPasswordRoute
  authSigninRoute: typeof authSigninRoute
  authSigninOtpRoute: typeof authSigninOtpRoute
  authSignupRoute: typeof authSignupRoute
  authVerify2faRoute: typeof authVerify2faRoute
  authVerifyOtpRoute: typeof authVerifyOtpRoute
}

const authRouteRouteChildren: authRouteRouteChildren = {
  authForgotPasswordRoute: authForgotPasswordRoute,
  authMagicLinkRoute: authMagicLinkRoute,
  authResetPasswordRoute: authResetPasswordRoute,
  authSigninRoute: authSigninRoute,
  authSigninOtpRoute: authSigninOtpRoute,
  authSignupRoute: authSignupRoute,
  authVerify2faRoute: authVerify2faRoute,
  authVerifyOtpRoute: authVerifyOtpRoute,
}

const authRouteRouteWithChildren = authRouteRoute._addFileChildren(
  authRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  authRouteRoute: authRouteRouteWithChildren,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
